// Recommended way, to include only the icons you need.
import {
  createIcons,
  SquareChevronLeft,
  SquareChartGantt,
  List,
  ShoppingCart,
  Scale,
  Settings,
  SquareUserRound,
  Barcode,
  NotebookTabs,
  Weight,
  BanknoteArrowDown,
  CircleQuestionMark,
  Search,
  ListFilter,
  ArrowDownAZ,
  ArrowUpZA,
  PackageOpen,
} from "lucide";

createIcons({
  icons: {
    SquareChevronLeft,
    SquareChartGantt,
    List,
    ShoppingCart,
    Scale,
    Settings,
    SquareUserRound,
    Barcode,
    NotebookTabs,
    Weight,
    BanknoteArrowDown,
    CircleQuestionMark,
    Search,
    ListFilter,
    ArrowDownAZ,
    ArrowUpZA,
    PackageOpen,
  },
  nameAttr: "data-lucide",
  inTemplates: true,
});
